#!/usr/bin/env bash
# Howler Agents -- Local Development Setup
#
# This script:
#   1. Creates .env from template if it does not exist
#   2. Starts the Docker Compose stack
#   3. Waits for all services to be healthy
#   4. Registers a default user and organization
#   5. Creates an API key
#   6. Prints the API key and MCP configuration
#
# Prerequisites: docker, docker compose, curl, jq

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Defaults
API_URL="http://localhost:8080"
DEFAULT_EMAIL="dev@howler-agents.local"
DEFAULT_PASSWORD="howler-dev-2026"
DEFAULT_ORG_NAME="Local Dev"
DEFAULT_ORG_SLUG="local-dev"
API_KEY_NAME="local-mcp"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[howler]${NC} $*"; }
warn() { echo -e "${YELLOW}[howler]${NC} $*"; }
fail() { echo -e "${RED}[howler]${NC} $*" >&2; exit 1; }

# -------------------------------------------------------------------
# Step 1: Create .env from template
# -------------------------------------------------------------------
log "Checking .env file..."

if [ ! -f "$SCRIPT_DIR/.env" ]; then
    cat > "$SCRIPT_DIR/.env" <<'ENVEOF'
# Howler Agents -- Local Development Environment
# Generated by setup.sh. Edit as needed.

# LLM API keys (at least one required for evolution runs)
ANTHROPIC_API_KEY=
OPENAI_API_KEY=

# LLM model overrides (defaults use Claude Sonnet)
# HOWLER_LLM_ACTING_MODEL=claude-sonnet-4-20250514
# HOWLER_LLM_EVOLVING_MODEL=claude-sonnet-4-20250514
# HOWLER_LLM_REFLECTING_MODEL=claude-sonnet-4-20250514

# JWT secret for auth (auto-generated for local dev)
JWT_SECRET=local-dev-jwt-secret-replace-in-production

# Service configuration
DATABASE_URL=postgresql+asyncpg://howler:howler@postgres:5432/howler_agents
REDIS_URL=redis://redis:6379/0
REST_PORT=8080
GRPC_PORT=50051
LOG_LEVEL=INFO
LOG_FORMAT=json
ENVEOF
    log "Created .env from template. Edit $SCRIPT_DIR/.env to add your LLM API keys."
else
    log ".env already exists, skipping creation."
fi

# -------------------------------------------------------------------
# Step 2: Start Docker Compose
# -------------------------------------------------------------------
log "Starting Docker Compose stack..."
docker compose -f "$SCRIPT_DIR/docker-compose.yml" up -d --build

# -------------------------------------------------------------------
# Step 3: Wait for health checks
# -------------------------------------------------------------------
log "Waiting for services to be healthy..."

MAX_WAIT=120
ELAPSED=0

wait_for_service() {
    local name="$1"
    local url="$2"
    local elapsed=0

    while [ $elapsed -lt $MAX_WAIT ]; do
        if curl -sf "$url" > /dev/null 2>&1; then
            log "$name is healthy."
            return 0
        fi
        sleep 2
        elapsed=$((elapsed + 2))
    done

    fail "$name failed to become healthy within ${MAX_WAIT}s."
}

wait_for_service "howler-service" "$API_URL/health"

# -------------------------------------------------------------------
# Step 4: Register default user
# -------------------------------------------------------------------
log "Registering default user ($DEFAULT_EMAIL)..."

REGISTER_RESPONSE=$(curl -sf -X POST "$API_URL/api/v1/auth/register" \
    -H "Content-Type: application/json" \
    -d "{
        \"email\": \"$DEFAULT_EMAIL\",
        \"password\": \"$DEFAULT_PASSWORD\",
        \"org_name\": \"$DEFAULT_ORG_NAME\",
        \"org_slug\": \"$DEFAULT_ORG_SLUG\"
    }" 2>&1) || true

if echo "$REGISTER_RESPONSE" | grep -q "access_token"; then
    ACCESS_TOKEN=$(echo "$REGISTER_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['access_token'])")
    log "User registered successfully."
elif echo "$REGISTER_RESPONSE" | grep -qi "already"; then
    warn "User already exists. Logging in instead..."
    LOGIN_RESPONSE=$(curl -sf -X POST "$API_URL/api/v1/auth/login" \
        -H "Content-Type: application/json" \
        -d "{
            \"email\": \"$DEFAULT_EMAIL\",
            \"password\": \"$DEFAULT_PASSWORD\"
        }") || fail "Login failed. Check credentials."
    ACCESS_TOKEN=$(echo "$LOGIN_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['access_token'])")
    log "Logged in successfully."
else
    fail "Registration failed: $REGISTER_RESPONSE"
fi

# -------------------------------------------------------------------
# Step 5: Create API key
# -------------------------------------------------------------------
log "Creating API key ($API_KEY_NAME)..."

APIKEY_RESPONSE=$(curl -sf -X POST "$API_URL/api/v1/auth/api-keys" \
    -H "Authorization: Bearer $ACCESS_TOKEN" \
    -H "Content-Type: application/json" \
    -d "{\"name\": \"$API_KEY_NAME\"}") || fail "Failed to create API key."

API_KEY=$(echo "$APIKEY_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['key'])")
API_KEY_PREFIX=$(echo "$APIKEY_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['key_prefix'])")

# -------------------------------------------------------------------
# Step 6: Print results
# -------------------------------------------------------------------
echo ""
echo -e "${CYAN}================================================================${NC}"
echo -e "${CYAN}  Howler Agents -- Local Development Ready${NC}"
echo -e "${CYAN}================================================================${NC}"
echo ""
echo -e "  API URL:       ${GREEN}$API_URL${NC}"
echo -e "  API Key:       ${GREEN}$API_KEY${NC}"
echo -e "  Key Prefix:    $API_KEY_PREFIX"
echo -e "  User Email:    $DEFAULT_EMAIL"
echo -e "  Organization:  $DEFAULT_ORG_NAME ($DEFAULT_ORG_SLUG)"
echo ""
echo -e "  ${YELLOW}Save your API key -- it is only shown once.${NC}"
echo ""
echo -e "${CYAN}--- MCP Configuration (for .mcp.json or .claude/mcp.json) ---${NC}"
echo ""
cat <<MCPEOF
{
  "mcpServers": {
    "howler-agents": {
      "command": "howler-agents",
      "args": ["serve"],
      "env": {
        "HOWLER_API_URL": "$API_URL",
        "HOWLER_API_KEY": "$API_KEY"
      }
    }
  }
}
MCPEOF
echo ""
echo -e "${CYAN}--- Quick Test ---${NC}"
echo ""
echo "  curl -s $API_URL/health"
echo "  curl -s -H 'Authorization: Bearer $API_KEY' $API_URL/api/v1/runs"
echo ""
echo -e "${CYAN}--- Stop ---${NC}"
echo ""
echo "  docker compose -f $SCRIPT_DIR/docker-compose.yml down"
echo ""
